apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.meta.name}}
  namespace: {{.Values.meta.namespace}}
  labels: {{include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{.Values.meta.name}}
  replicas: {{.Values.containers.openbeats.replicas}}
  template:
    metadata:
      labels: {{include "labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{.Values.containers.openbeats.name}}
        image: {{.Values.containers.openbeats.image.repository}}:{{.Values.containers.openbeats.image.tag}}
        imagePullPolicy: Always
        resources: {{toYaml .Values.containers.openbeats.resources | nindent 10}}
        ports:
        - containerPort: {{.Values.containers.openbeats.port}}
        readinessProbe:
          initialDelaySeconds: 5
          httpGet:
            port: {{.Values.containers.openbeats.port}}
            path: /health
        livenessProbe:
          initialDelaySeconds: 5
          httpGet:
            port: {{.Values.containers.openbeats.port}}
            path: /health
        volumeMounts:
        - name: config-yaml
          readOnly: true
          mountPath: "/secrets"
      volumes:
        - name: config-yaml
          secret:
            secretName: openbeats-api.config
