apiVersion: v1
kind: Service
metadata:
  name: { { .Values.meta.name } }
  namespace: { { .Values.meta.namespace } }
  labels: { { include "labels" . | nindent 4 } }
  annotations: { { include "elb-annotations" . | nindent 4 } }
spec:
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: { { .Values.containers.openbeats.port } }
    - name: http
      protocol: TCP
      port: 80
      targetPort: { { .Values.containers.openbeats.port } }
  selector:
    app: { { .Values.meta.name } }
