meta:
  provider: aws
  region: us-east-1
  clusterName: useast1.dev.openbeats716.com
  name: openbeats
  namespace: openbeats
  environment: development
containers:
  openbeats:
    name: openbeats
    image:
      repository: 318250923417.dkr.ecr.us-east-1.amazonaws.com/openbeats-api
      # Why is this CHANGETHIS? Mainly because the tag `latest` is an anti-pattern and I override this value at the helm upgrade step in CI
      tag: latest
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi
    port: 8000
    replicas: 1
loadBalancer:
  cert: arn:aws:acm:us-east-1:318250923417:certificate/f0526e5b-c228-4384-a5d0-8eb1d715c533
